const actionSupplier = {
  FETCH_SUPPLIER_REQUEST: "FETCH_SUPPLIER_REQUEST",
  FETCH_SUPPLIER_SUCCESS: "FETCH_SUPPLIER_SUCCESS",
  FETCH_SUPPLIER_FAILURE: "FETCH_SUPPLIER_FAILURE",

  CREATE_SUPPLIER_REQUEST: "CREATE_SUPPLIER_REQUEST",
  CREATE_SUPPLIER_SUCCESS: "CREATE_SUPPLIER_SUCCESS",
  CREATE_SUPPLIER_FAILURE: "CREATE_SUPPLIER_FAILURE",

  UPDATE_SUPPLIER_REQUEST: "UPDATE_SUPPLIER_REQUEST",
  UPDATE_SUPPLIER_SUCCESS: "UPDATE_SUPPLIER_SUCCESS",
  UPDATE_SUPPLIER_FAILURE: "UPDATE_SUPPLIER_FAILURE",

  DELETE_SUPPLIER_REQUEST: "DELETE_SUPPLIER_REQUEST",
  DELETE_SUPPLIER_SUCCESS: "DELETE_SUPPLIER_SUCCESS",
  DELETE_SUPPLIER_FAILURE: "DELETE_SUPPLIER_FAILURE",

  GET_SUPPLIER_BY_ID_REQUEST: "GET_SUPPLIER_BY_ID_REQUEST",
  GET_SUPPLIER_BY_ID_SUCCESS: "GET_SUPPLIER_BY_ID_SUCCESS",
  GET_SUPPLIER_BY_ID_FAILURE: "GET_SUPPLIER_BY_ID_FAILURE",
};

export default actionSupplier;
